Repository onosproject/gnxi-simulators, pull requests merged in 2019-08, with the labels that each got.

#69 Support insecure mode for gnmi target in the Docker image
  tools/docker_compose/docker-compose-gnmi.yml
  tools/docker_compose/docker-compose.yml
  tools/scripts/run_targets.sh
Labels: DO_NOT_MERGE

#68 Added in support for generating a gui cert
  docs/gnmi/gnmi_user_manual.md
  pkg/certs/generate_certs.sh
  pkg/certs/onfca.srl
  pkg/certs/onos-gui.crt
  pkg/certs/onos-gui.key
  pkg/certs/v3.ext
Labels: Type:Enhancement

#71 Try to reduce the size of simulator image
  Dockerfile
Labels: Component:gNMI

#72 Add openssl to alpine image to ensure certificates can be generated
  Dockerfile
Labels: Type:Bug
